services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=taskmanager'
      - 'POSTGRES_PASSWORD=neues_passwort'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'



