spring.application.name=e_rechnung

# Server Configuration
server.port=8081

# PostgreSQL Datenbank Konfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/e_rechnung
spring.datasource.username=postgres
spring.datasource.password=neues_passwort
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Konfiguration
# In Spring Boot 3 wird der Dialekt automatisch aus der JDBC-URL erkannt.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Migration
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration